spring:
  application:
    name: book-reader-service

server:
  port: ${PORT:0}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

ribbon:
  eureka:
    enabled: true


logging:
  level:
    org:
      springframework:
        web: debug